### ISSUE TITLE
Error using forge above forge 32.0.88

### ISSUE THREAD

**Issue by Powerless001** [iChun/Shatter#33]
When I boot up the game I get an error that says. "shatter (shatter) has failed to load correctly cannot register a generic event listener with addListener use addGenericListener" I think you may need to adjust something in the code maybe? I have no clue.

**Comment by ghost** [comment]
java.lang.IllegalArgumentException: Cannot register a generic event listener with addListener, use addGenericListener
		at net.minecraftforge.eventbus.EventBus.checkNotGeneric(EventBus.java:167) ~[eventbus-3.0.3-service.jar:?]
		at net.minecraftforge.eventbus.EventBus.checkNotGeneric(EventBus.java:162) ~[eventbus-3.0.3-service.jar:?]
		at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:173) ~[eventbus-3.0.3-service.jar:?]
		at me.ichun.mods.shatter.common.Shatter.lambda$null$0(Shatter.java:45) ~[?:9.0.0]
		at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:125) ~[?:?]
		at net.minecraftforge.fml.DistExecutor.runWhenOn(DistExecutor.java:109) ~[?:?]
		at me.ichun.mods.shatter.common.Shatter.<init>(Shatter.java:40) ~[?:9.0.0]
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
		at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:124) ~[?:?]
		at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:346) ~[?:?]
		at java.lang.Class.newInstance(Class.java:604) ~[?:?]
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:136) ~[?:32.0]
		at net.minecraftforge.fml.javafmlmod.FMLModContainer$ErroringConsumer.accept(FMLModContainer.java:190) ~[?:32.0]
		at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:113) ~[?:?]
		at net.minecraftforge.fml.ModList.lambda$null$11(ModList.java:135) ~[?:?]
		at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) [?:?]
		at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1624) [?:?]
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) [?:?]
		at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) [?:?]
		at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) [?:?]
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?]
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?]
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?]
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) [?:?]

**Comment by iChun** [comment]
Fixed in 9.0.1. Thanks for the report!
